title: Natália Sarellas
logo: /assets/2021-03-31.jpg
description: PhD Candidate at Universidade de São Paulo
show_downloads: true
theme: jekyll-theme-minimal

social-network-links:
  email: "sarellas@usp.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  linkedin: /natalia-sarellas
share-links-active:
  linkedin: true

