title: Natália Sarellas
logo: /assets/2021-03-31.jpg

show_downloads: true

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: 
  PhD Candidate in Economics, University of São Paulo.
  
theme: minima

#plugins:
 # - jekyll-feed
 # - jekyll-seo-tag


#author: Natália Sarellas
email: "nataliasarellas@gmail.com"

header_pages:
 # - about.md
  - portfolio.md
  - posts.md

show_excerpts: true
