title: Natália Sarellas
logo: /assets/2021-03-31.jpg

show_downloads: true

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Site pessoal e portfolio de Natália Sarellas, doutoranda em Economia pela Universidade de São Paulo.
  Aqui você encontra conteúdos sobre análise de dados, micro e macroeconomia, entre outros. 

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

  social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
     - { platform: github,         user_url: "https://github.com/sarellas" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/natalia-sarellas/" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

#author: Natália Sarellas
email: "natalia.sarellas@gmail.com"

header_pages:
 # - about.md
  - [portfolio.md](https://sarellas.github.io/portfolio.html)
  - [posts.md](https://sarellas.github.io/posts.html)

show_excerpts: true
