title: Natália Sarellas
logo: /assets/2021-03-31.jpg
description: PhD Candidate at Universidade de São Paulo
show_downloads: true
theme: minima

minima:
  social_links:
    - { platform: Linkedin,  user_url: "https://www.linkedin.com/in/natalia-sarellas/" }

#author: Natália Sarellas
email: "natalia.sarellas@gmail.com"

header_pages:
  - about.md
  - portfolio.md
  - posts.md

show_excerpts: true
